### ISSUE TITLE
tempfile.TemporaryDirectory() not supported in Python 2.7.11

### ISSUE THREAD

**Issue by lorenzschmid** [guyzmo/eagle-automation#6]
Having first installed `eagle-automation` via Python 2.7.11's `pip` the use of `pea diff` always lead to an error:

```
$ git difftool -t eaglediff
Traceback (most recent call last):
  File "/usr/local/bin/pea", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/eagle_automation/pea.py", line 92, in main
    return eagle_automation.diff.diff_main(verbose=args['--verbose'])
  File "/usr/local/lib/python2.7/site-packages/eagle_automation/diff.py", line 219, in diff_main
    diff(args['<from-file>'], args['<to-file>'], int(args['--page'] if args['--page'] else 0), args['--output'])
  File "/usr/local/lib/python2.7/site-packages/eagle_automation/diff.py", line 205, in diff
    diff_visual(from_file, to_file, page, output)
  File "/usr/local/lib/python2.7/site-packages/eagle_automation/diff.py", line 101, in diff_visual
    with tempfile.TemporaryDirectory() as workdir:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'
```

A closer look revealed that `tempfile.TemporaryDirectory()` got only introduced in [version 3.2](https://docs.python.org/3/library/tempfile.html) of the `tempfile` module and is therefore not present in versions of Python before version 3. I suggest that the [Python Egg](https://pypi.python.org/pypi/eagle_automation) for Python 2.7 gets removed.

**Comment by guyzmo** [comment]
I removed the python2.7 egg from pypi and I've modified the setup.py so it fails loudly when installing in python2. Thank you, and sorry for the loooooooooooooooong delay to fix that!
